[build]
  functions = "netlify/functions"
  command = "npm run build"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["pg-hstore", "mysql2"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/netlify_handler/:splat"
  status = 200